// src/app/components/header/header.component.ts
import {Component} from '@angular/core';
import {CommonModule} from '@angular/common';

@Component({
    standalone: true,
    selector: 'app-header',
    imports: [CommonModule],
    templateUrl: './header.component.html',
    styleUrl: './header.component.scss'
})
export class HeaderComponent {
}

<header class="mb-8">
  <h1 class="text-3xl font-bold bg-clip-text bg-gradient-to-r text-primary-600">
    Money Manager
  </h1>
  <p class="text-gray-600 mt-2">Трекер личных финансов</p>
</header>

// src/components/Header.tsx
export default function Header() {
    return (
        <header className="mb-8">
            <h1 className="text-3xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-primary-600 to-primary-800">Money Manager</h1>
            <p className="text-gray-600 mt-2">Трекер личных финансов</p>
        </header>
    );
}
