// src/app/components/add-transaction/add-transaction.component.ts
import {Component, inject, signal} from '@angular/core';
import {TransactionDTO} from '../../types/transaction';
import {CommonModule} from '@angular/common';
import {FormBuilder, ReactiveFormsModule, Validators} from '@angular/forms';
import {TransactionType} from '../../constants/transaction-type';
import {StoreService} from "../../services/store.service";

@Component({
    standalone: true,
    selector: 'app-add-transaction',
    imports: [CommonModule, ReactiveFormsModule],
    templateUrl: './add-transaction.component.html'
})

export class AddTransactionComponent {
    private readonly storeService = inject(StoreService);
    private readonly formBuilder = inject(FormBuilder);

    readonly form = this.formBuilder.group({
        type: ["Расход", Validators.required],
        category: ["", Validators.required],
        amount: [null, Validators.required],
        date: [new Date().toISOString().split("T")[0], Validators.required],
        description: [""]
    })

    categoriesSig = this.storeService.categoriesSig
    errorMessage = signal<string | null>(null);
    isLoading = signal(false);

    async addTransaction() {
        this.errorMessage.set(null);
        if (this.form.invalid) {
            this.errorMessage.set("Не заполнены все обязательные поля");
            return;
        }

        this.isLoading.set(true);
        try {
            const formValues = this.form.value;
            const type = formValues.type === 'Расход'
                ? TransactionType.EXPENSE
                : TransactionType.INCOME;

            const dto: TransactionDTO = {
                type,
                category: formValues.category!,
                amount: formValues.amount!,
                date: formValues.date!,
                description: formValues.description ?? "",
            };
            await this.storeService.addTransaction(dto);
            this.form.patchValue({amount: null, description: ""})
        } catch (err) {
            this.errorMessage.set("Ошибка при добавлении транзакции");
            console.error(err);
        } finally {
            this.isLoading.set(false);
        }
    }
}

<div class="p-4 border-t bg-gray-50">
    <form [formGroup]="form" (ngSubmit)="addTransaction()">
        <div class="grid grid-cols-1 md:grid-cols-4 gap-4">
            <div class="md:col-span-4">
                <div class="flex items-center justify-between">
                    <h3 class="text-lg font-medium mb-4">Добавить транзакцию</h3>
                    <span class="flex justify-end text-small text-gray-500 mb-4">* Обязательное поле</span>
                </div>


                <div class="grid grid-cols-1 md:grid-cols-4 gap-2">
                    <div>
                        <label class="block text-xs text-gray-500 mb-1">Тип*
                            <select formControlName="type"
                                    class="w-full p-2 border hover:bg-gray-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary-400">
                                <option>Расход</option>
                                <option>Доход</option>
                            </select>
                        </label>
                    </div>

                    <div>
                        <label class="block text-xs text-gray-500 mb-1">Категория*
                            <input formControlName="category"
                                   list="categories"
                                   class="w-full p-2 border rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary-400"/>
                            <datalist id="categories">
                                @for (category of categoriesSig(); track category.id) {
                                    <option [value]="category.name"></option>
                                }
                            </datalist>
                        </label>
                    </div>

                    <div>
                        <label class="block text-xs text-gray-500 mb-1">Сумма*
                            <input formControlName="amount"
                                   type="number" step="0.01" min="0"
                                   placeholder="0.00"
                                   class="w-full p-2 border rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary-400"/>
                        </label>
                    </div>

                    <div>
                        <label class="block text-xs text-gray-500 mb-1">Дата*
                            <input formControlName="date"
                                   type="date"
                                   class="w-full p-2 border rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary-400"/>
                        </label>
                    </div>

                    <div class="md:col-span-4">
                        <label class="block text-xs text-gray-500 mb-1">Описание
                            <input formControlName="description"
                                   type="text"
                                   class="w-full p-2 border rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary-400"/>
                        </label>
                    </div>
                </div>
            </div>
        </div>

        <div class="flex justify-end mt-6 gap-4">
            @if (errorMessage()) {
                <div class="p-2 text-red-700 rounded text-sm opacity-0">
                    {{ errorMessage() }}
                </div>
            }
            <button type="submit"
                    class="bg-primary-600 hover:bg-primary-700 text-white px-4 py-2 rounded-lg transition-colors duration-300 text-sm z-10">

                @if (isLoading()) {
                    <span>Добавление...</span>
                } @else {
                    <span>Добавить</span>
                }
            </button>
        </div>
    </form>
</div>

// src/components/forms/AddTransaction.tsx
import type {TransactionDTO} from "../../types/Transaction.ts";
import {useEffect, useRef} from "react";
import {useCategoriesQuery, useCreateTransactionMutation} from "../../hooks/useTransactionHook";

export default function AddTransaction() {
    const typeRef = useRef<HTMLSelectElement>(null);
    const categoryRef = useRef<HTMLInputElement>(null);
    const amountRef = useRef<HTMLInputElement>(null);
    const dateRef = useRef<HTMLInputElement>(null);
    const descriptionRef = useRef<HTMLInputElement>(null);

    const {data: categories = []} = useCategoriesQuery();
    const {mutate: createTransaction} = useCreateTransactionMutation();

    useEffect(() => {
        if (dateRef.current) {
            dateRef.current.value = new Date().toISOString().split("T")[0];
        }
    }, []);

    return (
        <div>
            <div className="p-4 border-t bg-gray-50">
                <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
                    <div className="md:col-span-4">
                        <h3 className="text-lg font-medium mb-4">Добавить транзакцию</h3>
                        <div className="grid grid-cols-1 md:grid-cols-4 gap-2">
                            <div>
                                <label className="block text-xs text-gray-500 mb-1">Тип</label>
                                <select ref={typeRef}
                                        className="w-full p-2 border hover:bg-gray-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary-400">
                                    <option>Расход</option>
                                    <option>Доход</option>
                                </select>
                            </div>
                            <div>
                                <label className="block text-xs text-gray-500 mb-1">Категория</label>
                                <input
                                    list="categories"
                                    ref={categoryRef}
                                    className="w-full p-2 border rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary-400"/>
                                <datalist id="categories"
                                          className="w-full p-2 border rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary-400">
                                    {
                                        categories.map(category => {
                                            return <option key={category.id} value={category.name}/>
                                        })
                                    }
                                </datalist>
                            </div>
                            <div>
                                <label className="block text-xs text-gray-500 mb-1">Сумма</label>
                                <input ref={amountRef}
                                       type="number"
                                       className="w-full p-2 border rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary-400"
                                       placeholder="0.00"/>
                            </div>
                            <div>
                                <label className="block text-xs text-gray-500 mb-1">Дата</label>
                                <input ref={dateRef}
                                       type="date"
                                       className="w-full p-2 border rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary-400"
                                       placeholder="0.00"/>
                            </div>
                            <div className="md:col-span-4">
                                <label className="block text-xs text-gray-500 mb-1">Описание</label>
                                <input ref={descriptionRef}
                                       type="text"
                                       className="w-full p-2 border rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary-400"/>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="flex justify-end mt-6">
                    <button
                        className="bg-primary-600 hover:bg-primary-700 text-white px-4 py-2 rounded-lg transition-colors duration-300 text-sm z-10"
                        onClick={
                            async () => {
                                try {
                                    const type: string = typeRef.current?.value === "Расход" ? "EXPENSE" : "INCOME";
                                    const dto: TransactionDTO = {
                                        type: type,
                                        category: String(categoryRef.current?.value),
                                        amount: Number(Number(amountRef.current?.value).toFixed(2)),
                                        date: String(dateRef.current?.value),
                                        description: String(descriptionRef.current?.value)
                                    }
                                    createTransaction(dto);
                                } catch (error) {
                                    console.error("Ошибка во время добавления транзакции:", error)
                                }
                            }
                        }>
                        Добавить
                    </button>
                </div>
            </div>
        </div>
    );
}
