// src/app/components/transactions-history/transactions-history.component.ts
import {Component, computed, inject, signal} from '@angular/core';
import {StoreService} from "../../services/store.service";
import {SortingRules, TransactionUtils} from "../../utils/transactions.utils";
import {TransactionFieldName} from "../../constants/transaction-field-name";
import {SortingDirection} from "../../constants/sorting-direction";
import {FormattingUtils} from "../../utils/formatting.utils";
import {FormsModule} from "@angular/forms";
import {TransactionFilterService} from "../../services/transaction.filter.service";
import {Transaction} from "../../types/transaction";
import {TransactionEditModalComponent} from "../transaction-edit-modal/transaction-edit-modal.component";

@Component({
    standalone: true,
    selector: 'app-transactions-history',
    imports: [
        FormsModule,
        TransactionEditModalComponent
    ],
    templateUrl: './transactions-history.component.html'
})
export class TransactionsHistoryComponent {
    private readonly storeService = inject(StoreService);
    private readonly transactionFilterService = inject(TransactionFilterService);

    private readonly transactionsSig = this.storeService.transactionsSig;
    private readonly filterSig = this.transactionFilterService.filterSig;

    private readonly filteredTransactions = computed(() => {
        console.log("filtering transactions in \"transactions-history table\" by", this.filterSig());
        return TransactionUtils.filter(this.transactionsSig(), this.filterSig());
    })

    readonly hoveredIdSig = signal<number | null>(null);
    readonly visibleDescriptionIdSig = signal<number | null>(null);
    readonly startEditingSig = signal<Transaction | null>(null);

    readonly sortingSig = signal<SortingRules>({
        sortingBy: TransactionFieldName.DATE,
        direction: SortingDirection.DESC
    });

    readonly transactions = computed(() => {
        console.log("sorting transactions history by", this.sortingSig());
        return TransactionUtils.sort(this.filteredTransactions(), this.sortingSig())
    });

    toggleSorting(fieldName: string): void {
        const field = fieldName as TransactionFieldName;
        this.sortingSig.update(previous => {
            if (previous.sortingBy === field) {
                return {
                    sortingBy: field,
                    direction: previous.direction === SortingDirection.ASC ? SortingDirection.DESC : SortingDirection.ASC
                };
            }
            return {
                sortingBy: field,
                direction: SortingDirection.DESC
            };
        })
    }

    toggleDescription(id: number): void {
        this.visibleDescriptionIdSig.update(current => current === id ? null : id);
    }

    openEditWindow(transaction: Transaction): void {
        console.log("Open edit window:", transaction);
        this.startEditingSig.set(transaction);
    }

    cancelEdit(): void {
        this.startEditingSig.set(null);
    }

    async saveEdited(transaction: Transaction): Promise<void> {
        await this.storeService.updateTransaction(transaction);
    }

    async delete(id: number): Promise<void> {
        await this.storeService.deleteTransaction(id);
    }

    protected readonly TransactionFieldName = TransactionFieldName;
    protected readonly Object = Object;
    protected readonly FormattingUtils = FormattingUtils;
}

<div class="p-4 border-b flex justify-between items-center">
    <h2 class="text-xl text-light-1 cursor-default">История транзакций</h2>
    <div class="flex gap-2">
        <button class="flex items-center px-3 py-1 gap-1 rounded-lg text-sm text-dark-1 bg-light-1 hover:bg-blue-2 transition-color duration-200">
            <span class="material-symbols-outlined text-sm">filter_alt</span>
            Фильтр
        </button>
        <div class="relative flex px-3 py-1 gap-1 items-center rounded-lg bg-light-1">
            <span class="material-symbols-outlined text-sm text-dark-1">search</span>
            <input
                    class="bg-transparent text-sm outline-none text-dark-1"
                    placeholder="Поиск..."
            />
        </div>
    </div>
</div>

<div class="overflow-x-auto">
    <table class="w-full table-fixed">
        <thead>
        <tr class="text-left bg-light-1 text-xs text-dark-1 uppercase">
            @for (field of Object.values(TransactionFieldName); track field) {
                @if (!(field === TransactionFieldName.DESCRIPTION)) {
                    <th class="px-6 py-0.5" (click)="toggleSorting(field)">
                        <span class="cursor-pointer">{{ field }}
                            <span class="material-symbols-outlined text-xs">
                                @if (sortingSig().sortingBy === field) {
                                    {{ sortingSig().direction === 'ASC' ? 'arrow_drop_up' : 'arrow_drop_down' }}
                                } @else {
                                    {{ "  " }}
                                }
                            </span>
                        </span>
                    </th>
                }
            }
        </tr>
        </thead>
        <tbody>
            @for (transaction of transactions(); track transaction.id) {
                <tr (click)="toggleDescription(transaction.id)"
                    (mouseenter)="hoveredIdSig.set(transaction.id)"
                    (mouseleave)="hoveredIdSig.set(null)"
                    class="hover:bg-dark-3 transition-colors duration-150">

                    <td class="p-3 overflow-hidden whitespace-nowrap text-light-1 cursor-default">
                        {{ transaction.type === 'EXPENSE' ? 'Расход' : 'Доход' }}
                    </td>
                    <td class="p-3 overflow-hidden whitespace-nowrap text-light-1 cursor-default">
                        {{ transaction.category }}
                    </td>
                    <td class="p-3 overflow-hidden whitespace-nowrap text-light-1 cursor-default">
                        {{ FormattingUtils.formatDate(transaction.date) }}
                    </td>
                    <td class="p-3 py-1 mt-2 grid grid-cols-2 justify-between overflow-hidden whitespace-nowrap fonts-monospace cursor-default {{ transaction.type === 'EXPENSE' ? 'text-red' : 'text-green'}}">
                        {{ transaction.amount.toFixed(2) }}₽
                        @if (hoveredIdSig() === transaction.id) {
                            <div class="flex justify-end gap-7">
                                <button (click)="openEditWindow(transaction)"
                                        class="text-yellow transition-opacity duration-200">
                                    <span class="material-symbols-outlined">edit</span>
                                </button>
                                <button (click)="delete(transaction.id)"
                                        class="text-red transition-opacity duration-200">
                                    <span class="material-symbols-outlined">delete</span>
                                </button>
                            </div>
                        }
                    </td>
                </tr>

                @if (visibleDescriptionIdSig() === transaction.id) {
                    <!-- Описание (всплывающее) -->
                    <tr (mouseenter)="hoveredIdSig.set(transaction.id)"
                        (mouseleave)="hoveredIdSig.set(null)">
                        <td colspan="4" class="px-3 py-2 text-sm text-purple bg-dark-2 cursor-default">
                            {{ transaction.description || 'Нет описания' }}
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>
@if (startEditingSig()) {
    <app-edit-transaction-modal
            [transaction]="startEditingSig()!"
            (save)="saveEdited($event)"
            (cancel)="cancelEdit()">
    </app-edit-transaction-modal>
}

// src/components/forms/TransactionsHistory.tsx
import {deleteTransactionMutation, filteredTransactionsQuery} from "../../hooks/transactions.ts";
import {useMemo, useState} from "react";
import {type Transaction, TransactionFieldName} from "../../types/Transaction";
import {SortingDirection, type SortingRules, transactionUtils} from "../../util/TransactionsUtils.ts";

export default function TransactionsHistory() {
    const [sorting, setSorting] = useState<SortingRules>({
        sortingBy: TransactionFieldName.Date,
        direction: "DESC"
    });

    const {data: transactions = []} = filteredTransactionsQuery();
    const {mutate: deleteTransaction} = deleteTransactionMutation();

    const processedTransactions: Array<Transaction> = useMemo(() => {
        return transactionUtils.sort(transactions, sorting);
    }, [transactions, sorting]);

    return (
        <>
            <div>
                <div className="flex justify-between items-center p-5 border-b">
                    <div className="flex items-center gap-4">
                        <h2 className="text-xl font-semibold">История транзакций</h2>
                    </div>
                    <div className="flex gap-2">
                        <button
                            className="flex items-center gap-1 text-sm bg-gray-100 hover:bg-gray-200 px-3 py-1 rounded-lg transition duration-300">
                            <span className="material-symbols-outlined text-sm">filter_alt</span>
                            Фильтр
                        </button>
                        <div className="relative">
                            <div className="flex items-center gap-1 bg-gray-100 px-3 py-1 rounded-lg">
                                {/*https://fonts.google.com/icons*/}
                                <span className="material-symbols-outlined text-sm text-gray-500">search</span>
                                <input className="bg-transparent border-none outline-none text-sm w-36"
                                       placeholder="Поиск..."/>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="overflow-x-auto">
                <table className="w-full">
                    <thead className="bg-gray-50">
                    <tr>
                        {
                            Object.values(TransactionFieldName).map(fieldName => {
                                const isActive = sorting.sortingBy === fieldName;
                                const isDirectionAsc = sorting.direction === SortingDirection.ASC;

                                return (
                                    <th
                                        key={fieldName}
                                        onClick={() => {
                                            setSorting((prevState) => {
                                                if (prevState.sortingBy === fieldName) {
                                                    return {
                                                        sortingBy: fieldName,
                                                        direction: prevState.direction === "ASC" ? "DESC" : "ASC"
                                                    }
                                                }
                                                return {
                                                    sortingBy: fieldName,
                                                    direction: "DESC"
                                                };
                                            });
                                        }}
                                        className="px-6 py-1 bg-gray-100 text-left text-xs font-medium text-gray-500 uppercase tracking-wider cursor-pointer"
                                    >
                                        <span className="flex gap-1">
                                            {fieldName}
                                            {isActive && (
                                                <span className="material-symbols-outlined text-xs resize-triggers">
                                                    {isDirectionAsc ? "arrow_drop_up" : "arrow_drop_down"}
                                                </span>
                                            )}
                                        </span>
                                    </th>
                                )
                            })
                        }
                    </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-200">
                    {
                        processedTransactions
                            .map(transaction => {
                                const transactionType = transaction.type;
                                return (
                                    <tr key={transaction.id}
                                        className="group hover:bg-gray-100 transition-colors duration-150">
                                        <td className="px-4 py-4 whitespace-nowrap cursor-pointer">
                                            <div className="w-24 flex items-center">
                                                <div
                                                    className="h-10 w-10 flex-shrink-0 bg-primary-100 rounded-full flex items-center justify-center mr-3">
                                            <span
                                                className="material-symbols-outlined text-primary-600">shopping_bag</span>
                                                </div>
                                                <div>
                                                    <div className="font-medium">{transaction.category}</div>
                                                    <div className="text-sm text-gray-500">Online</div>
                                                </div>
                                            </div>
                                        </td>
                                        <td className="px-6 py-2 whitespace-nowrap">{transactionType === "EXPENSE" ? "Расход" : "Доход"}</td>
                                        <td className="px-6 py-4 whitespace-nowrap">
                                            {new Date(transaction.date).toLocaleDateString("ru-RU", {
                                                day: "numeric",
                                                month: "long",
                                                year: "numeric"
                                            }).replace(" г.", "")}
                                        </td>
                                        <td className={`px-6 py-4 whitespace-nowrap ${transactionType === "EXPENSE" ? "text-red-500" : "text-green-500"} font-medium`}
                                            onDoubleClick={() => console.log("clicked on amount")}>{transaction.amount.toFixed(2)}₽
                                        </td>
                                        <td className="px-6 py-4 whitespace-nowrap flex justify-between">
                                            <span
                                                onDoubleClick={() => console.log("clicked on description")}
                                                className="flex text-gray-500">
                                                {transaction.description}
                                            </span>
                                            <button onClick={() => deleteTransaction(transaction.id)}
                                                    className="opacity-0 text-red group-hover:opacity-90 transition-opacity duration-200 ml-2">
                                                <span className="material-symbols-outlined text-base">delete</span>
                                            </button>
                                        </td>
                                    </tr>
                                );
                            })
                    }
                    </tbody>
                </table>
            </div>
        </>
    );
}
